@startuml
title Sequence Diagram - Adapter Pattern
actor User
participant "tripTop: \nFrontend" as TriptopFrontend
participant "hotelController: \nHotelController" as HotelController
participant "hotelService: \nHotelService" as HotelService
participant "hotelApiAdapter: \nHotelApiAdapter" as HotelApiAdapter
participant "externalHotelAPI: \nExternalHotelAPI" as ExternalHotelAPI


User -> TriptopFrontend: Goes to hotel detail page
TriptopFrontend -> HotelController : getHotelDetails(hotelId)
HotelController -> HotelService : retrieveHotelDetails(hotelId)
HotelService -> HotelApiAdapter : fetchHotelDetails(hotelId)
HotelApiAdapter -> ExternalHotelAPI : ?(hotelId)
ExternalHotelAPI --> HotelApiAdapter : returns raw hotel data
HotelApiAdapter --> HotelService : returns adapted hotel data
HotelService --> HotelController : returns processed hotel details
HotelController --> TriptopFrontend : returns hotel details
TriptopFrontend --> User : shows hotel details

@enduml