@startuml
!include <C4/C4_Component>

title C4 Component Diagram - Triptop Applicatie

Person(User, "Reiziger", "Iemand die de app gebruikt voor reizen")

System_Boundary(c3, "Triptop Applicatie") {
    Component(Frontend, "Frontend", "Web Applicatie", "Geeft UI weer en verstuurt requests")
    Component(Backend, "Backend", "Spring Boot API", "Verwerkt requests en voert logica uit")
    Component(AuthenticationService, "Authentication Service", "Component: Spring Boot Service", "Behandeld Authenticatie")
}

System_Boundary(c4, "Externe API's") {
    Component(ExternelAPI1, "External API 1", "Extern Systeem", "Ontvangt geauthenticeerde verzoeken")
    Component(ExternalAPI2, "External API 2", "Extern Systeem", "Ontvangt geauthenticeerde verzoeken")
}

Rel(User, Frontend, "Interactie met de")
Rel(Frontend, Backend, "Stuurt requests naar")
Rel(Backend, AuthenticationService, "Maakt gebruik van")
Rel(AuthenticationService, Backend, "Stuurt geauthenticeerde token terug naar de")
Rel(Backend, ExternelAPI1, "Stuurt geauthenticeerde token naar")
Rel(Backend, ExternalAPI2, "Stuurt geauthenticeerde token naar")

@enduml