@startuml
title C4 Class Diagram - Triptop applicatie

class HotelController {
    - final HotelServicePort: HOTELSERVICEPORT
    + getHotelDetails(int HotelId) : Hotel
}

interface HotelServicePort {
    + retrieveHotelDetails(int HotelId) : Hotel
}

class Hotel {
    - int: Id
    - String: Naam
    - String: Beschrijving
    - String: Locatie
}

class HotelServiceImpl {
    - final HOTELSERVICEADAPTER : HotelServiceAdapter
    + retrieveHotelDetails(int HotelId) : Hotel
}

class HotelServiceAdapter {
    - final BOOKINGAPI : BookingAPI
    + fetchHotelDetails(int HotelId) : Hotel
}

class BookingAPI {
    <<external>>
}

HotelController --> HotelServicePort : Maakt gebruik van
HotelController --> Hotel : : Maakt gebruik van

HotelServicePort <|.. HotelServiceImpl : Implementeert

HotelServiceImpl --> HotelServiceAdapter : Haalt data op van
HotelServiceAdapter --> BookingAPI : Haalt data op van
@enduml
