@startuml
actor User
participant "AuthController: \nAuthController" as AC
participant "AuthFacade: \nAuthFacade" as AF
participant "UserService: \nUserService" as US
participant "TokenService: \nTokenService" as TS
participant "LoggerService: \nLoggerService" as LS

User -> AC: POST /auth/login (username, password)
AC -> AF: login(username, password)
AF -> US: login(username, password)
US -> US: Send HTTP request to login URL
US -> AF: Return token
AF -> LS: log("Login successful/failed")
AF -> AC: Return token
AC -> User: Return token

User -> AC: POST /auth/checkAccess (token, username, application)
AC -> AF: checkAppAccess(token, username, application)
AF -> TS: checkAppAccess(token, username, application)
TS -> TS: Send HTTP request to check access URL
TS -> AF: Return access response
AF -> AC: Return access response
AC -> User: Return access response

@enduml
